Repository radical-cybertools/radical.pilot, pull requests merged in 2018-03, with the labels that each got.

#1517 Issue/1513
  examples/11_unit_input_folder.py
  examples/make_folders.py
  setup.py
  src/radical/pilot/agent/staging_input/default.py
  src/radical/pilot/agent/staging_output/default.py
  src/radical/pilot/staging_directives.py
  tests/staging-testing-sandbox/sample-data/multi-folder/folder-1/file-1
  tests/staging-testing-sandbox/sample-data/multi-folder/folder-1/file-2
  tests/staging-testing-sandbox/sample-data/multi-folder/folder-2/file-1
  tests/staging-testing-sandbox/sample-data/multi-folder/folder-2/file-2
  tests/staging-testing-sandbox/sample-data/sample_configuration_staging_input.json
  tests/staging-testing-sandbox/sample-data/sample_configuration_staging_output.json
  tests/staging-testing-sandbox/sample-data/single-file
  tests/staging-testing-sandbox/sample-data/single-folder/file-1
  tests/staging-testing-sandbox/sample-data/single-folder/file-2
  tests/test_agent_staging_input_component_default.py
  tests/test_agent_staging_output_component_default.py
Labels: feature

#1575 Fix/issue 1514 (ii)
  tests/test_agent_staging_input_component_default.py
  tests/test_agent_staging_output_component_default.py
  tests/test_issue_1514/test_rp_integration.py
  tests/test_tarball_umgr.py
Labels: testing

#1544 Fix/issue 1466
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/agent/lm/base.py
  src/radical/pilot/agent/lm/mpiexec.py
  src/radical/pilot/agent/lm/mpirun.py
  src/radical/pilot/agent/lm/mpirun_ccmrun.py
  src/radical/pilot/agent/lm/mpirun_dplace.py
  src/radical/pilot/agent/lm/mpirun_rsh.py
  src/radical/pilot/agent/lm/orte.py
  src/radical/pilot/agent/lm/orte_lib.py
  src/radical/pilot/agent/lm/poe.py
  src/radical/pilot/agent/lm/rsh.py
  src/radical/pilot/agent/lm/runjob.py
  src/radical/pilot/agent/lm/ssh.py
  src/radical/pilot/configs/resource_local.json
Labels: type:bug

#1536 Feature/hombre
  src/radical/pilot/agent/scheduler/base.py
  src/radical/pilot/agent/scheduler/hombre.py
  src/radical/pilot/agent/staging_output/default.py
  src/radical/pilot/compute_pilot.py
  src/radical/pilot/configs/resource_local.json
  src/radical/pilot/umgr/scheduler/backfilling.py
  src/radical/pilot/umgr/scheduler/base.py
  src/radical/pilot/umgr/staging_input/default.py
  src/radical/pilot/utils/component.py
  src/radical/pilot/worker/update.py
Labels: type:performance

#1537 Feature/fifo
  src/radical/pilot/agent/scheduler/base.py
  src/radical/pilot/agent/scheduler/continuous_fifo.py
  src/radical/pilot/agent/scheduler/hombre.py
  tests/test_integration_fifo_scheduler.py
Labels: type:feature, type:performance

#1541 Fix/issue 1501
  src/radical/pilot/unit_manager.py
Labels: type:bug

#1540 Feature/config docs
  docs/architecture/configuration.md
Labels: type:documentation

#1543 Feature/gpu franklin
  src/radical/pilot/compute_unit_description.py
Labels: type:documentation
