Repository radical-cybertools/radical.pilot, pull requests merged in 2019-04, with the labels that each got.

#1839 Adding Travis check for PR code only
  .travis.yml
  src/radical/pilot/agent/rm/yarn.py
Labels: layer:rp, priority:high, topic:testing

#1844 Fix/issue 1826
  examples/archive/12_partitions.py
Labels: priority:low, type:documentation

#1845 fix bridges default partition
  src/radical/pilot/configs/resource_xsede.json
Labels: comp:pmgr:launcher, priority:low, topic:configuration, topic:resource, type:bug

#1846 fix var expansion
  src/radical/pilot/agent/bootstrap_0.sh
  src/radical/pilot/agent/rm/ccm.py
  src/radical/pilot/agent/rm/fork.py
  src/radical/pilot/agent/rm/lsf.py
  src/radical/pilot/agent/rm/pbspro.py
  src/radical/pilot/agent/rm/sge.py
  src/radical/pilot/agent/rm/slurm.py
  src/radical/pilot/agent/rm/torque.py
Labels: priority:critical, topic:api, topic:resource, type:bug

#1850 remove events.md from install
  setup.py
Labels: comp:agent:bootstrapper, priority:critical, topic:deployment, topic:resource, type:bug
