Repository radical-cybertools/radical.pilot, pull requests merged in 2020-08, with the labels that each got.

#2184 fix rcfg listing
  src/radical/pilot/session.py
Labels: comp:session, priority:high, topic:api, type:bug

#2179 Add needed documentation
  bin/radical-pilot-resources
  docs/source/user_guide/00_getting_started.rst
Labels: type:documentation, type:feature

#2178 Remove SKIP_FAILED
  docs/source/datastaging.rst
  src/radical/pilot/constants.py
Labels: type:documentation

#2174 Port prof util to python3
  bin/radical-pilot-prte2prof
Labels: topic:profiling

#2173 Fix summit jsrun conf
  examples/config.json
  src/radical/pilot/configs/resource_ornl.json
  src/radical/pilot/utils/session.py
Labels: topic:configuration, type:bug

#2196 Pip error messages
  src/radical/pilot/agent/bootstrap_0.sh
Labels: comp:agent:bootstrapper, priority:high

#2125 Feature/worker 2
  examples/misc/task_overlay.cfg
  examples/misc/task_overlay.frontera.cfg
  examples/misc/task_overlay.py
  examples/misc/task_overlay_master.py
  examples/misc/task_overlay_worker.py
  src/radical/pilot/agent/agent_0.py
  src/radical/pilot/agent/bootstrap_0.sh
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/agent/launch_method/base.py
  src/radical/pilot/task_overlay/master.py
  src/radical/pilot/task_overlay/request.py
  src/radical/pilot/task_overlay/worker.py
  tests/test_cases/unit.000000.json
  tests/test_cases/unit.000005.json
Labels: comp:agent:executor, priority:high, topic:api, topic:communication, topic:execution, type:feature, type:performance

#2189 Update documentation
  LICENSE.md
  README.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
Labels: priority:medium, type:documentation

#2163 support cheyenne
  bin/radical-pilot-create-static-ve
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/agent/launch_method/mpirun.py
  src/radical/pilot/configs/resource_ncar.json
Labels: comp:agent:bootstrapper, comp:agent:executor, comp:pmgr:launcher, priority:critical, topic:configuration, topic:execution, topic:resource, type:enhancement

#2146 Feature/job name
  src/radical/pilot/compute_pilot_description.py
  src/radical/pilot/pmgr/launching/default.py
  tests/test_launcher/test_launcher.py
Labels: comp:pmgr, comp:pmgr:launcher, priority:medium, topic:api, type:feature

#2199 Remove `munch` as a dependency and update RU and RS version requirement
  setup.py
  src/radical/pilot/agent/bootstrap_0.sh
  tests/test_launcher/test_launcher.py
  tests/test_lm/test_unit/test_mpirun.py
Labels: priority:medium, topic:deployment

#2200 fix cache keys for rs urls
  src/radical/pilot/pmgr/launching/default.py
Labels: comp:pmgr:launcher, priority:medium, topic:data, type:enhancement

#2202 Fix/indent
  src/radical/pilot/utils/prof_utils.py
Labels: priority:low, topic:testing, type:question, type:refactor

#2197 Debug pilot/unit duration
  .codecov.yml
  src/radical/pilot/agent/executing/archive/abds.py
  src/radical/pilot/agent/executing/archive/orte.py
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/agent/executing/shell.py
  src/radical/pilot/agent/executing/shell_fs.py
  src/radical/pilot/agent/executing/sleep.py
  src/radical/pilot/utils/prof_utils.py
  tests/test_prof_utils.py
Labels: layer:analytics, type:performance

#2198 handling SAGA job description attribute SystemArchitecture (with SMT, CPUArchitecture, GPUArchitecture)
  src/radical/pilot/configs/resource_llnl.json
  src/radical/pilot/configs/resource_ornl.json
  src/radical/pilot/configs/resource_xsede.json
  src/radical/pilot/pmgr/launching/default.py
  tests/test_launcher/test_launcher.py
Labels: comp:agent:executor, layer:saga, priority:medium, topic:execution

#2208 Fix for db close/disconnect method
  bin/radical-pilot-cleanup
  bin/radical-pilot-close-session
  bin/radical-pilot-fetch-json
  bin/radical-pilot-inspect
  bin/radical-pilot-stats
Labels: priority:medium, type:bug

#2209 Update for Summit's resource config (added option `gpumps` explicitly)
  src/radical/pilot/configs/resource_ornl.json
Labels: priority:medium, topic:configuration, topic:resource:summit, type:enhancement

#2210 Fixed cfg for Summit PRTE LM (for consistency)
  src/radical/pilot/configs/resource_ornl.json
Labels: priority:medium, topic:configuration, topic:resource:summit, type:enhancement

#2203 Fix/exports
  src/radical/pilot/constants.py
  src/radical/pilot/states.py
Labels: priority:low, type:refactor

#2211 Hotfix/prte profiling
  src/radical/pilot/agent/launch_method/prte.py
Labels: comp:agent:executor, priority:critical, topic:profiling, type:bug
