Repository radical-cybertools/radical.pilot, pull requests merged in 2021-03, with the labels that each got.

#2340 Feature/funcs v2 mpi
  bin/radical-pilot-agent-funcs-mpi
  examples/09_mpi_task_function.py
  examples/config.json
  setup.py
  src/radical/pilot/__init__.py
  src/radical/pilot/agent/__init__.py
  src/radical/pilot/agent/bootstrap_0.sh
  src/radical/pilot/agent/executing/base.py
  src/radical/pilot/agent/executing/funcs_mpi.py
  src/radical/pilot/agent/mpi_worker.py
  src/radical/pilot/configs/resource_xsede.json
  src/radical/pilot/pytask.py
  src/radical/pilot/task_description.py
Labels: comp:agent, comp:agent:executor, layer:rp, type:feature

#2337 Updates for PRTE2 LM
  docs/source/events.md
  src/radical/pilot/agent/launch_method/prte.py
  src/radical/pilot/agent/launch_method/prte2.py
  src/radical/pilot/agent/resource_manager/base.py
  src/radical/pilot/agent/resource_manager/lsf_summit.py
  src/radical/pilot/agent/scheduler/continuous.py
  tests/unit_tests/test_cases/task.000000.json
  tests/unit_tests/test_cases/task.000005.json
  tests/unit_tests/test_scheduler/test_continuous.py
Labels: priority:medium, topic:execution, type:enhancement

#2342 trivial fix nodelist -> nodefile
  src/radical/pilot/agent/launch_method/srun.py
Labels: priority:high, topic:execution, type:bug

#2338 add_pilot() also accepts pilot dict
  .github/workflows/python-app.yml
  src/radical/pilot/task_manager.py
  tests/unit_tests/test_tmgr/test_tmgr.py
Labels: comp:umgr, priority:high, topic:api, type:enhancement

#2343 New resource - Andes@ORNL
  src/radical/pilot/configs/agent_rhea.json
  src/radical/pilot/configs/resource_ornl.json
  src/radical/pilot/session.py
Labels: priority:medium, topic:configuration, topic:resource, type:enhancement

#2346 python 2 -> 3 fix for shebangs
  bin/radical-pilot-agent
  bin/radical-pilot-agent-funcs
  bin/radical-pilot-agent-statepush
  bin/radical-pilot-bridge
  bin/radical-pilot-bson2json
  bin/radical-pilot-cleanup
  bin/radical-pilot-close-session
  bin/radical-pilot-component
  bin/radical-pilot-fetch-db
  bin/radical-pilot-fetch-json
  bin/radical-pilot-fetch-logfiles
  bin/radical-pilot-fetch-profiles
  bin/radical-pilot-inspect
  bin/radical-pilot-limits.py
  bin/radical-pilot-prte2prof
  bin/radical-pilot-resources
  bin/radical-pilot-run-session
  bin/radical-pilot-stats
  bin/radical-pilot-version
  examples/00_getting_started.py
  examples/01_task_details.py
  examples/02_failing_tasks.py
  examples/03_multiple_pilots.py
  examples/04_scheduler_selection.py
  examples/05_task_input_data.py
  examples/06_task_output_data.py
  examples/07_shared_task_data.py
  examples/08_task_environment.py
  examples/09_mpi_tasks.py
  examples/10_pre_and_post_exec.py
  examples/11_task_input_data_tar.py
  examples/11_task_input_folder.py
  examples/12_task_function.py
  examples/archive/12_partitions.py
  examples/data_staging/io_staging_dict.py
  examples/data_staging/io_staging_pipeline.py
  examples/data_staging/io_staging_shared.py
  examples/data_staging/io_staging_simple.py
  examples/docs/chained_tasks.py
  examples/docs/coupled_tasks.py
  examples/docs/mpi_tasks.py
  examples/docs/simple_bot.py
  examples/docs/simple_bot_mult_res.py
  examples/error_handling.py
  examples/getting_started_osg.py
  examples/getting_started_osg_2.py
  examples/helloworld_mpi.py
  examples/helloworld_threads.py
  examples/misc/backfilling.py
  examples/misc/backfilling_recovery.py
  examples/misc/colocated.py
  examples/misc/hello_synapse.py
  examples/misc/ordered_pipelines.py
  examples/misc/rp_app_comm.py
  examples/misc/rp_app_master.py
  examples/misc/rp_app_worker.py
  examples/misc/wl_shape_02.py
  examples/rp_analytics.py
  setup.py
  tests/bin/radical-pilot-test-issue
Labels: priority:critical, topic:deployment, type:bug

#2349 avoid a termination race
  src/radical/pilot/tmgr/scheduler/base.py
Labels: comp:umgr, priority:medium, topic:communication, type:bug

#2357 Fix #2347
  setup.py
Labels: comp:agent:bootstrapper, priority:critical, topic:deployment, type:bug

#2358 removing cuda env from lm base
  src/radical/pilot/agent/launch_method/base.py
  src/radical/pilot/agent/launch_method/ssh.py
  tests/unit_tests/test_cases/task.000000.json
  tests/unit_tests/test_cases/task.000005.json
  tests/unit_tests/test_cases/task.000009.json
Labels: comp:agent:executor, priority:low, topic:execution, type:enhancement

#2360 Fixed launch command for PRTE2 LM
  src/radical/pilot/agent/launch_method/prte2.py
  tests/unit_tests/test_cases/task.000000.json
  tests/unit_tests/test_cases/task.000005.json
Labels: priority:medium, topic:execution

#2356 remove add_resource_config
  docs/source/machconf.rst
  examples/00_getting_started.py
  examples/misc/dynamic_ec2_pilot.py
  src/radical/pilot/constants.py
  src/radical/pilot/session.py
  tests/component_tests/test_session.py
Labels: comp:session, priority:medium, topic:api, topic:resource, type:bug
