Repository radical-cybertools/radical.pilot, pull requests merged in 2021-04, with the labels that each got.

#2353 No nodes overlapping between different tags (Continuous scheduler)
  src/radical/pilot/agent/scheduler/base.py
  src/radical/pilot/agent/scheduler/continuous.py
  tests/unit_tests/test_scheduler/test_cases_continuous/task.000000.json
  tests/unit_tests/test_scheduler/test_cases_continuous/task.000001.json
  tests/unit_tests/test_scheduler/test_cases_continuous/task.000002.json
  tests/unit_tests/test_scheduler/test_cases_continuous/task.000003.json
  tests/unit_tests/test_scheduler/test_cases_continuous/test_continuous.json
  tests/unit_tests/test_scheduler/test_continuous.py
Labels: comp:agent:scheduler, priority:medium, type:enhancement

#2351 ensure that RU lock names are unique
  src/radical/pilot/pilot_manager.py
  src/radical/pilot/task_manager.py
  src/radical/pilot/utils/component.py
Labels: priority:medium, type:bug

#2350 fix ve isolation for prep_env
  bin/radical-pilot-create-static-ve
  src/radical/pilot/agent/agent_0.py
  src/radical/pilot/agent/scheduler/base.py
Labels: priority:medium, topic:deployment, type:enhancement

#2367 need uids earlier
  src/radical/pilot/pilot_manager.py
  src/radical/pilot/task_manager.py
Labels: comp:pmgr, comp:umgr, priority:critical, type:bug

#2362 Fix/dispatches
  .github/workflows/bridges.yml
  .github/workflows/comet.yml
  .github/workflows/summit.yml
  README.md
  tests/integration_tests/README.md
  tests/integration_tests/batch_scripts/bridges2.sh
  tests/integration_tests/batch_scripts/comet.sh
  tests/integration_tests/batch_scripts/summit.sh
Labels: priority:medium, topic:testing, type:enhancement

#2369 fix missing event updates
  src/radical/pilot/configs/pmgr_default.json
  src/radical/pilot/task_manager.py
Labels: comp:umgr, priority:critical, topic:communication, type:bug

#2371 apply `RP_*` env vars to raptor tasks
  src/radical/pilot/raptor/worker.py
Labels: comp:raptor, priority:medium, topic:execution, type:enhancement

#2372 Remove obsolete attribute `tag` in `TaskDescription`
  src/radical/pilot/agent/scheduler/archive/continuous_summit.py
  src/radical/pilot/agent/scheduler/continuous.py
  src/radical/pilot/task_description.py
  tests/unit_tests/test_scheduler/test_continuous.py
Labels: priority:medium

#2376 Fixed example "07_..."
  examples/07_shared_task_data.py
  tests/unit_tests/test_cases/task.000010.json
Labels: priority:low

#2377 Flags to keep `prun` aware of gpus (PRTE2 LM)
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/agent/launch_method/prte2.py
  tests/unit_tests/test_cases/task.000005.json
Labels: priority:medium, topic:execution, type:enhancement

#2386 Update description strings
  docs/source/_themes/armstrong/layout.html
  docs/source/conf.py
  src/radical/pilot/pilot.py
  src/radical/pilot/pilot_description.py
  src/radical/pilot/task_description.py
  tests/unit_tests/test_task/__init__.py
  tests/unit_tests/test_task/test_task.py
Labels: priority:medium, type:documentation
