Repository radical-cybertools/radical.pilot, pull requests merged in 2021-07, with the labels that each got.

#2416 Cleaned list of dependencies
  bin/radical-pilot-create-static-ve
  setup.py
  src/radical/pilot/agent/bootstrap_0.sh
Labels: priority:medium, topic:deployment

#2415 Separate cpu/gpu utilization
  src/radical/pilot/utils/prof_utils.py
Labels: layer:analytics, priority:medium, topic:data, topic:profiling, type:enhancement

#2389 Hotfix/stager error
  examples/05_task_input_data.py
  examples/11_task_input_folder.py
  examples/make_folders.py
  src/radical/pilot/pilot_manager.py
  src/radical/pilot/raptor/master.py
  src/radical/pilot/raptor/worker.py
  src/radical/pilot/task.py
  src/radical/pilot/utils/component.py
  src/radical/pilot/worker/stager.py
Labels: comp:agent:stager, priority:high, topic:data, type:bug

#2418 artifact upload
  .github/workflows/python-app.yml
  examples/config.json
  src/radical/pilot/configs/resource_local.json
Labels: layer:analytics, layer:rp, priority:high, topic:profiling, topic:testing, type:enhancement

#2421 Use methods from the new module `host` within RU (>=1.6.7)
  bin/radical-pilot-create-static-ve
  setup.py
  src/radical/pilot/agent/bootstrap_0.sh
  src/radical/pilot/agent/launch_method/base.py
  src/radical/pilot/agent/launch_method/mpirun.py
  src/radical/pilot/agent/resource_manager/cobalt.py
  src/radical/pilot/agent/resource_manager/slurm.py
  src/radical/pilot/configs/resource_anl.json
  src/radical/pilot/pmgr/launching/default.py
  tests/unit_tests/test_rm/test_cobalt.py
  tests/unit_tests/test_rm/test_slurm.py
  tests/unit_tests/test_rm/test_torque.py
Labels: priority:medium, topic:api, type:enhancement

#2420 Fixed resource set file record `cpu_index_using: logical` (for jsrun)
  src/radical/pilot/agent/launch_method/jsrun.py
  tests/integration_tests/test_lm/test_jsrun/test_1/res_set
  tests/integration_tests/test_lm/test_jsrun/test_10/res_set
  tests/integration_tests/test_lm/test_jsrun/test_11/res_set
  tests/integration_tests/test_lm/test_jsrun/test_12/res_set
  tests/integration_tests/test_lm/test_jsrun/test_2/res_set
  tests/integration_tests/test_lm/test_jsrun/test_3/res_set
  tests/integration_tests/test_lm/test_jsrun/test_5/res_set
  tests/integration_tests/test_lm/test_jsrun/test_7/res_set
  tests/integration_tests/test_lm/test_jsrun/test_9/res_set
  tests/unit_tests/test_cases/task.000000.json
  tests/unit_tests/test_cases/task.000003.json
  tests/unit_tests/test_cases/task.000005.json
  tests/unit_tests/test_cases/task.000006.json
  tests/unit_tests/test_cases/task.000007.json
  tests/unit_tests/test_cases/task.000013.json
  tests/unit_tests/test_executing/test_cases/test_base.json
Labels: priority:medium, topic:resource:summit, type:bug

#2425 Clean up configs
  src/radical/pilot/configs/agent_summit_sa.json
  src/radical/pilot/configs/resource_anl.json
  src/radical/pilot/configs/resource_ornl.json
  src/radical/pilot/configs/resource_princeton.json
  src/radical/pilot/configs/resource_tacc.json
  src/radical/pilot/configs/resource_xsede.json
Labels: priority:medium, topic:configuration, type:bug

#2424 Fixed pilot staging for input directories
  src/radical/pilot/worker/stager.py
  tests/component_tests/test_stager.py
Labels: priority:high, type:bug
