Repository radical-cybertools/radical.pilot, pull requests merged in 2022-02, with the labels that each got.

#2487 fixing srun version command
  src/radical/pilot/agent/launch_method/srun.py
  tests/unit_tests/test_lm/test_srun.py
Labels: priority:critical, layer:rp, comp:pmgr:launcher, comp:agent

#2499 yet another remaining python -> python3 rename
  src/radical/pilot/agent/bootstrap_0.sh
Labels: type:bug, topic:resource, priority:critical, comp:agent:bootstrapper, topic:deployment

#2494 Added rp.session.* to gitignore Fixes #2493
  .gitignore
Labels: priority:low

#2501 fix metric setup / lookup in tmgr
  src/radical/pilot/task_manager.py
  tests/unit_tests/test_tmgr/test_tmgr.py
Labels: type:bug, topic:api, priority:medium, comp:umgr

#2502 Update launch method `aprun`
  src/radical/pilot/agent/launch_method/aprun.py
  tests/unit_tests/test_lm/test_aprun.py
  tests/unit_tests/test_lm/test_cases/task.000000.json
  tests/unit_tests/test_lm/test_cases/task.000003.json
  tests/unit_tests/test_lm/test_cases/task.000004.json
  tests/unit_tests/test_lm/test_cases/task.000005.json
  tests/unit_tests/test_lm/test_cases/task.000006.json
  tests/unit_tests/test_lm/test_cases/task.000013.json
Labels: priority:medium, type:refactor

#2495 ensure correct env for raptor
  src/radical/pilot/agent/launch_method/base.py
Labels: type:bug, topic:resource, priority:critical, comp:agent:executor, comp:raptor

#2500 better error message on missing tools
  src/radical/pilot/agent/launch_method/base.py
  src/radical/pilot/agent/launch_method/mpiexec.py
  src/radical/pilot/agent/launch_method/mpirun.py
  tests/unit_tests/test_lm/test_mpiexec.py
  tests/unit_tests/test_lm/test_mpirun.py
Labels: type:enhancement, priority:low, comp:agent:executor

#2503 Summit - CPU indexing
  src/radical/pilot/agent/launch_method/jsrun.py
  src/radical/pilot/agent/resource_manager/lsf.py
  src/radical/pilot/configs/resource_ornl.json
Labels: priority:medium, topic:resource:summit

#2513 Documentation tutorial notebook
  docs/source/tutorial.ipynb
Labels: type:documentation

#2515 fix capture of exit code
  src/radical/pilot/agent/executing/popen.py
Labels: type:bug, topic:execution, priority:high

#2514 Remove task log and the state_history as they are no longer supported Fixes #2508
  docs/source/user_guide/02_failing_tasks.rst
Labels: type:documentation

#2512 LM's base env with activated VE
  src/radical/pilot/agent/launch_method/base.py
Labels: type:bug, priority:medium

#2517 RM parameter `_launch_order`
  src/radical/pilot/agent/resource_manager/base.py
  src/radical/pilot/configs/resource_anl.json
  tests/unit_tests/test_rm/test_base.py
Labels: type:bug, priority:medium

#2525 Tests fixes
  src/radical/pilot/pmgr/launching/default.py
  tests/unit_tests/test_rm/test_base.py
  tests/unit_tests/test_tmgr/test_tmgr.py
Labels: topic:testing, priority:medium

#2523 Config handling (using `merge`) in `ComponentManager` class
  src/radical/pilot/utils/component.py
  tests/component_tests/test_component.py
Labels: layer:utils, priority:medium

#2521 get backfilling scheduler back in sync
  src/radical/pilot/tmgr/scheduler/backfilling.py
  src/radical/pilot/tmgr/scheduler/base.py
  src/radical/pilot/tmgr/scheduler/round_robin.py
Labels: type:bug, topic:resource, priority:medium, comp:tmgr:scheduler

#2522 use proper shell quoting
  src/radical/pilot/agent/launch_method/base.py
  tests/unit_tests/test_lm/test_cases/task.000003.json
  tests/unit_tests/test_lm/test_cases/task.000004.json
  tests/unit_tests/test_lm/test_cases/task.000005.json
  tests/unit_tests/test_lm/test_cases/task.000006.json
  tests/unit_tests/test_lm/test_cases/task.000007.json
  tests/unit_tests/test_lm/test_cases/task.000013.json
  tests/unit_tests/test_lm/test_cases/task.000014.json
Labels: type:bug, priority:critical, topic:execution, comp:agent:executor

#2529 fix dep versions
  setup.py
Labels: priority:medium, topic:deployment
