Repository radical-cybertools/radical.pilot, pull requests merged in 2022-01, with the labels that each got.

#2476 Fixed configs (env isolation)
  src/radical/pilot/configs/resource_anl.json
  src/radical/pilot/configs/resource_debug.json
  src/radical/pilot/configs/resource_rutgers.json
  src/radical/pilot/configs/resource_tacc.json
  src/radical/pilot/configs/resource_xsede.json
Labels: topic:resource, priority:medium, topic:configuration

#2484 set RP_RANK on non-MPI tasks
  src/radical/pilot/agent/executing/popen.py
  tests/unit_tests/test_executing/test_popen.py
Labels: type:bug, priority:critical, topic:execution, comp:pmgr:launcher

#2434 Change custom `repr()` output.
  src/radical/pilot/pilot.py
  src/radical/pilot/task.py
Labels: type:enhancement, priority:medium
