Repository radical-cybertools/radical.pilot, pull requests merged in 2022-09, with the labels that each got.

#2683 Added option `-gpu` for IBM Spectrum MPI (MPIRun LM)
  src/radical/pilot/agent/launch_method/base.py
  src/radical/pilot/agent/launch_method/mpirun.py
  tests/unit_tests/test_lm/test_cases/task.000004.json
  tests/unit_tests/test_lm/test_cases/task.000015.json
  tests/unit_tests/test_lm/test_mpirun.py
Labels: type:feature, topic:execution, priority:medium, comp:agent:executor, topic:resource:summit

#2682 only use major and minor version for `prep_env` spec
  bin/radical-pilot-create-static-ve
  src/radical/pilot/pilot.py
Labels: type:enhancement, priority:high, topic:deployment

#2678 Sync term signals
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/agent/scheduler/base.py
  tests/unit_tests/test_scheduler/test_continuous.py
Labels: topic:termination, type:enhancement, priority:medium, comp:agent:executor, comp:agent:scheduler

#2666 Fix/issue 2590
  docs/architecture/concepts/mpi_executor/client.py
  examples/data_staging/io_staging_all.py
  src/radical/pilot/agent/staging_input/default.py
  src/radical/pilot/agent/staging_output/default.py
  src/radical/pilot/pilot.py
  src/radical/pilot/pilot_manager.py
  src/radical/pilot/pmgr/launching/base.py
  src/radical/pilot/session.py
  src/radical/pilot/staging_directives.py
  src/radical/pilot/task.py
  src/radical/pilot/task_manager.py
  src/radical/pilot/tmgr/scheduler/base.py
  src/radical/pilot/tmgr/staging_input/default.py
  src/radical/pilot/tmgr/staging_output/default.py
  tests/unit_tests/test_launcher/test_launcher.py
  tests/unit_tests/test_pilot/test_pilot.py
Labels: topic:data, topic:api, type:enhancement, priority:medium

#2669 add rcfg inspection utilities
  src/radical/pilot/utils/misc.py
  tests/unit_tests/test_utils.py
Labels: topic:api, type:enhancement, priority:medium, comp:session

#2689 Fix tests cleanup
  tests/component_tests/test_session.py
  tests/unit_tests/test_utils.py
Labels: topic:testing, type:enhancement, priority:medium

#2153 Provide Docker recipe and instructions for testing.
  .travis.yml
  docker/README.md
  docker/radicalpilot.dockerfile
  docker/rp-complete.dockerfile
  docker/stack.yml
Labels: type:feature, topic:testing, priority:medium

#2695 Use a linking target for staging directives references.
  docs/source/datastaging.rst
Labels: type:documentation, type:enhancement, priority:medium

#2693 make pilot launch and bootstrap CWD-independent
  src/radical/pilot/agent/bootstrap_0.sh
  src/radical/pilot/pmgr/launching/base.py
Labels: type:enhancement, priority:high, comp:pmgr:launcher, comp:agent:bootstrapper, topic:deployment

#2575 feature interactive job
  docs/source/faq.rst
  examples/config.json
  src/radical/pilot/agent/resource_manager/base.py
  src/radical/pilot/configs/resource_ornl.json
  src/radical/pilot/configs/resource_tacc.json
  src/radical/pilot/pmgr/launching/base.py
  src/radical/pilot/session.py
Labels: type:feature, topic:resource, layer:rp, priority:low, topic:configuration

#2615 Update error handling and logging.
  bin/radical-pilot-create-static-ve
  examples/misc/raptor.py
  src/radical/pilot/agent/agent_0.py
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/pytask.py
  src/radical/pilot/raptor/worker_mpi.py
  src/radical/pilot/utils/serializer.py
Labels: topic:data, type:enhancement, priority:medium, comp:tmgr

#2654 bulk submission for parsl executor
  examples/parsl/colmena_rp/colmena_rp.py
  examples/parsl/colmena_rp/raptor_worker.py
  examples/parsl/colmena_rp/sim.py
  examples/parsl/map_reduce.py
  src/radical/pilot/agent/agent_0.py
  src/radical/pilot/agent/executing/parsl_rp.py
Labels: type:performance, topic:execution, type:enhancement, priority:high, comp:tmgr, comp:raptor

#2705 interactive bridges2
  src/radical/pilot/configs/resource_xsede.json
Labels: layer:rp, priority:low, topic:configuration

#2703 Default LM in Summit resource config
  src/radical/pilot/configs/resource_ornl.json
Labels: type:enhancement, priority:medium, topic:resource:summit

#2704 Cleanup configs
  bin/radical-pilot-inspect
  docs/source/machconf.rst
  src/radical/pilot/configs/agent_cray.json
  src/radical/pilot/configs/agent_cray_aprun.json
  src/radical/pilot/configs/agent_scale.json
  src/radical/pilot/configs/resource_anl.json
  src/radical/pilot/configs/resource_debug.json
  src/radical/pilot/configs/resource_llnl.json
  src/radical/pilot/configs/resource_ncar.json
  src/radical/pilot/configs/resource_ornl.json
  src/radical/pilot/configs/resource_princeton.json
  src/radical/pilot/configs/resource_rutgers.json
  src/radical/pilot/configs/resource_tacc.json
  src/radical/pilot/configs/resource_xsede.json
Labels: topic:resource, type:enhancement, priority:medium, topic:configuration

#2715 Split LMs for Summit among dedicated configurations
  src/radical/pilot/configs/resource_ornl.json
  tests/unit_tests/test_launcher/test_launcher.py
Labels: type:enhancement, priority:medium, topic:resource:summit, topic:configuration

#2681 task description update
  .pylintrc
  docs/source/user_guide/11_containerized_compute_tasks.rst
  examples/00_getting_started.py
  examples/09_mpi_tasks.py
  examples/data_staging/io_staging_shared.py
  examples/misc/colocated.py
  examples/misc/env.py
  examples/misc/hello_synapse.py
  examples/misc/ordered_pipelines.py
  examples/misc/raptor.cfg
  examples/misc/raptor.py
  examples/misc/raptor_master.py
  examples/misc/raptor_worker.py
  examples/misc/wl_shape_02.py
  src/radical/pilot/agent/agent_0.py
  src/radical/pilot/agent/launch_method/aprun.py
  src/radical/pilot/agent/launch_method/ccmrun.py
  src/radical/pilot/agent/launch_method/fork.py
  src/radical/pilot/agent/launch_method/ibrun.py
  src/radical/pilot/agent/launch_method/jsrun.py
  src/radical/pilot/agent/launch_method/mpirun.py
  src/radical/pilot/agent/launch_method/prte.py
  src/radical/pilot/agent/launch_method/srun.py
  src/radical/pilot/agent/scheduler/base.py
  src/radical/pilot/agent/scheduler/continuous.py
  src/radical/pilot/agent/scheduler/continuous_colo.py
  src/radical/pilot/agent/scheduler/flux.py
  src/radical/pilot/agent/scheduler/hombre.py
  src/radical/pilot/raptor/master.py
  src/radical/pilot/raptor/worker_mpi.py
  src/radical/pilot/task_description.py
  src/radical/pilot/tmgr/scheduler/backfilling.py
  src/radical/pilot/utils/prof_utils.py
  tests/integration_tests/test_config/task.000000.json
  tests/unit_tests/test_agent_0/test_agent_0.py
  tests/unit_tests/test_executing/test_cases/test_base.json
  tests/unit_tests/test_lm/test_cases/task.000000.json
  tests/unit_tests/test_lm/test_cases/task.000001.json
  tests/unit_tests/test_lm/test_cases/task.000002.json
  tests/unit_tests/test_lm/test_cases/task.000003.json
  tests/unit_tests/test_lm/test_cases/task.000004.json
  tests/unit_tests/test_lm/test_cases/task.000005.json
  tests/unit_tests/test_lm/test_cases/task.000006.json
  tests/unit_tests/test_lm/test_cases/task.000007.json
  tests/unit_tests/test_lm/test_cases/task.000008.json
  tests/unit_tests/test_lm/test_cases/task.000009.json
  tests/unit_tests/test_lm/test_cases/task.000010.json
  tests/unit_tests/test_lm/test_cases/task.000011.json
  tests/unit_tests/test_lm/test_cases/task.000012.json
  tests/unit_tests/test_lm/test_cases/task.000013.json
  tests/unit_tests/test_lm/test_cases/task.000014.json
  tests/unit_tests/test_lm/test_cases/task.000015.json
  tests/unit_tests/test_lm/test_fork.py
  tests/unit_tests/test_lm/test_srun.py
  tests/unit_tests/test_scheduler/test_cases/task.000000.json
  tests/unit_tests/test_scheduler/test_continuous.py
  tests/unit_tests/test_scheduler/test_continuous_ordered.py
  tests/unit_tests/test_task/test_task.py
Labels: type:documentation, topic:api, type:enhancement, priority:high, type:refactor

#2716 Update and consolidate docker documentation.
  docker/README.md
  docker/compose.yml
  docker/radicalpilot.dockerfile
  docker/rp-complete.dockerfile
  docker/stack.yml
Labels: type:documentation, topic:api, topic:resource, type:enhancement, priority:medium, topic:configuration

#2721 added `apt update` command for analytics-tests setup
  .github/workflows/python-app.yml
Labels: topic:testing, priority:high

#2691 Clarify and troubleshoot raptor.py example.
  docker/README.md
  examples/misc/raptor.cfg
  examples/misc/raptor.py
  examples/misc/raptor_master.py
  examples/misc/raptor_worker.py
  src/radical/pilot/pytask.py
Labels: topic:documentation, priority:medium, topic:configuration

#2701 fix raptor example cfg, prep_env doc string
  src/radical/pilot/pilot.py
Labels: type:enhancement, priority:low, topic:configuration

#2722 td naming
  src/radical/pilot/agent/launch_method/aprun.py
  src/radical/pilot/agent/launch_method/mpirun.py
  src/radical/pilot/agent/scheduler/base.py
  src/radical/pilot/agent/scheduler/continuous_colo.py
Labels: priority:high
