Repository radical-cybertools/radical.pilot, pull requests merged in 2023-12, with the labels that each got.

#3033 Feature/task process id
  src/radical/pilot/agent/bootstrap_0.sh
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/agent/staging_output/default.py
  src/radical/pilot/task.py
  tests/unit_tests/test_executing/test_popen.py
Labels: type:feature

#3105 fixed `Task._update` method (`description` attribute)
  src/radical/pilot/task.py
Labels: type:bug, priority:high, comp:tmgr

#3106 Fix/raptor example
  examples/misc/raptor.cfg
  examples/misc/raptor.py
Labels: type:bug, topic:documentation, priority:medium

#3109 Doc/agent scheduler
  docs/source/apidoc.rst
  src/radical/pilot/agent/scheduler/continuous.py
Labels: topic:documentation, type:enhancement, priority:high, comp:agent:scheduler

#3110 "fix typos"
  src/radical/pilot/agent/scheduler/continuous.py
Labels: comp:agent:scheduler

#3111 Feature/bragg.py
  examples/misc/bragg.py
Labels: topic:documentation, type:enhancement, priority:low
