Repository radical-cybertools/radical.pilot, pull requests merged in 2023-04, with the labels that each got.

#2873 add documentation for missing properties
  src/radical/pilot/pilot.py
  src/radical/pilot/task.py
Labels: topic:documentation, type:enhancement, priority:medium, comp:tmgr, comp:pmgr

#2890 fix task environment setup for raptor tasks
  src/radical/pilot/raptor/worker.py
  src/radical/pilot/raptor/worker_mpi.py
  src/radical/pilot/task_description.py
Labels: type:bug, topic:execution, priority:high, comp:raptor

#2862 fix issue_2588
  docs/source/machconf.rst
Labels: topic:documentation, layer:rp, topic:configuration

#2891 Docs/nb section3 supported platform Polaris
  docs/source/supported/polaris.rst
Labels: topic:documentation

#2838 add rank documentation
  docs/source/overview.rst
  src/radical/pilot/task_description.py
Labels: topic:documentation, topic:api, type:enhancement, priority:medium, comp:tmgr

#2907 removed `codecov` from test requirements
  requirements-tests.txt
Labels: topic:testing, priority:medium

#2908 Fix/virtenv fallback
  src/radical/pilot/agent/bootstrap_0.sh
Labels: type:bug, priority:high, comp:agent:bootstrapper, topic:deployment

#2913 adding interactive config to UVA
  src/radical/pilot/configs/resource_uva.json
Labels: topic:configuration

#2892 Feature/raptor api 2
  bin/radical-pilot-raptor-master
  bin/radical-pilot-raptor-worker
  examples/misc/ddmd.py
  examples/misc/raptor.cfg
  examples/misc/raptor.py
  examples/misc/raptor_master.py
  examples/misc/raptor_simple.py
  examples/misc/raptor_worker.py
  setup.py
  src/radical/pilot/__init__.py
  src/radical/pilot/agent/agent_0.py
  src/radical/pilot/agent/agent_n.py
  src/radical/pilot/agent/bootstrap_0.sh
  src/radical/pilot/agent/executing/base.py
  src/radical/pilot/agent/executing/flux.py
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/agent/executing/sleep.py
  src/radical/pilot/agent/launch_method/base.py
  src/radical/pilot/agent/scheduler/base.py
  src/radical/pilot/agent/staging_output/default.py
  src/radical/pilot/configs/agent_default.json
  src/radical/pilot/configs/agent_default_sa.json
  src/radical/pilot/db/database.py
  src/radical/pilot/pilot.py
  src/radical/pilot/pilot_manager.py
  src/radical/pilot/raptor/master.py
  src/radical/pilot/raptor/worker.py
  src/radical/pilot/raptor/worker_default.py
  src/radical/pilot/raptor/worker_mpi.py
  src/radical/pilot/raptor_tasks.py
  src/radical/pilot/task_description.py
  src/radical/pilot/task_manager.py
  src/radical/pilot/utils/component.py
  src/radical/pilot/worker/update.py
  tests/test_raptor/test_raptor.py
  tests/unit_tests/test_executing/test_cases/test_base.json
  tests/unit_tests/test_executing/test_popen.py
  tests/unit_tests/test_raptor/test_master.py
  tests/unit_tests/test_tmgr/test_tmgr.py
  tests/unit_tests/test_utils.py
Labels: comp:raptor

#2859 recover bootstrap_0_stop event
  src/radical/pilot/utils/prof_utils.py
  tests/unit_tests/test_cases/bootstrap_0.prof
  tests/unit_tests/test_scheduler/test_base.py
  tests/unit_tests/test_scheduler/test_continuous.py
  tests/unit_tests/test_utils.py
Labels: type:bug, priority:high, comp:agent:bootstrapper, topic:profiling

#2917 fixed the process of requesting a correct number of cores/gpus
  src/radical/pilot/agent/resource_manager/base.py
  src/radical/pilot/pmgr/launching/base.py
Labels: type:bug, priority:high, comp:pmgr:launcher, comp:agent
