Repository radical-cybertools/radical.pilot, pull requests merged in 2023-10, with the labels that each got.

#3051 comment out test code
  bin/radical-pilot-bridge
  src/radical/pilot/session.py
Labels: topic:testing, type:enhancement, priority:medium

#3054 fixed RM LSF for Lassen (+ fixed platform config)
  src/radical/pilot/agent/resource_manager/lsf.py
  src/radical/pilot/configs/resource_llnl.json
Labels: type:bug, topic:resource, topic:configuration

#3048 Remove MDB
  examples/README.md
Labels: topic:documentation

#3056 remove debug remnant
  bin/radical-pilot-bridge
Labels: type:bug, priority:critical, comp:session, topic:configuration

#3063 added supported platform Lassen
  docs/source/supported.rst
  docs/source/supported/lassen.rst
  src/radical/pilot/configs/resource_llnl.json
Labels: topic:documentation

#3064 fix command and detect MPICH mpiexec lm
  src/radical/pilot/agent/launch_method/mpiexec.py
  tests/unit_tests/test_lm/test_mpiexec.py
Labels: type:bug, type:enhancement, layer:rp, comp:pmgr:launcher

#3044 Feature/mpi raptor tutorial
  .github/workflows/docs.yml
  .github/workflows/run-rp-notebook.yml
  docs/source/tutorials/raptor.ipynb
  docs/source/tutorials/raptor_mpi.ipynb
Labels: topic:documentation, layer:rp, comp:raptor

#3067 updated the "Describing Tasks" tutorial
  docs/source/tutorials/describing_tasks.ipynb
Labels: topic:documentation

#3066 clear RAPTOR and Configuration tutorials notebooks
  docs/source/tutorials/configuration.ipynb
  docs/source/tutorials/raptor.ipynb
Labels: topic:documentation, layer:rp, priority:medium

#3035 Option `--ppn` in MPIEXEC LM
  docs/source/supported/polaris.rst
  src/radical/pilot/agent/launch_method/mpiexec.py
  tests/unit_tests/test_lm/test_cases/task.000003.json
  tests/unit_tests/test_lm/test_cases/task.000020.json
Labels: topic:resource, topic:execution, type:enhancement, priority:high
