Repository radical-cybertools/radical.pilot, pull requests merged in 2023-09, with the labels that each got.

#2998 stub slurm test
  bin/radical-pilot-test-slurm
Labels: topic:testing, topic:resource, type:enhancement, priority:medium, comp:agent:executor, topic:configuration

#3027 Upload session when testing notebooks
  .github/workflows/docs.yml
  .github/workflows/run-rp-notebook.yml
Labels: topic:documentation, topic:testing

#3029 deprecated `python.system_packages`
  .readthedocs.yml
Labels: topic:documentation

#3034 one profile per rank
  src/radical/pilot/raptor/worker.py
Labels: type:bug, priority:high, topic:profiling, comp:raptor
