Repository radical-cybertools/radical.pilot, pull requests merged in 2023-05, with the labels that each got.

#2921 Feature/mpi flag
  src/radical/pilot/agent/launch_method/fork.py
  src/radical/pilot/agent/launch_method/rsh.py
  src/radical/pilot/agent/launch_method/ssh.py
  src/radical/pilot/task_description.py
  tests/unit_tests/test_lm/test_fork.py
  tests/unit_tests/test_lm/test_rsh.py
  tests/unit_tests/test_lm/test_ssh.py
  tests/unit_tests/test_rm/test_fork.py
  tests/unit_tests/test_task/test_task.py
Labels: topic:api, type:enhancement, priority:medium, comp:tmgr

#2883 Docs/nb section3 raptor
  docs/source/tutorials/getting_started.ipynb
  docs/source/tutorials/raptor.ipynb
  src/radical/pilot/pilot_manager.py
  src/radical/pilot/raptor/worker_default.py
Labels: topic:documentation, type:enhancement, priority:medium, comp:raptor

#2912 added resource configurations for NCSA Delta
  src/radical/pilot/configs/resource_ncsa.json
  src/radical/pilot/session.py
  tests/component_tests/test_session.py
Labels: type:feature, topic:configuration

#2879 Docs/nb section3 task description
  docs/source/envs.rst
  docs/source/tutorials/describing_tasks.ipynb
  docs/source/tutorials/getting_started.ipynb
  docs/source/tutorials/raptor.ipynb
  requirements-devel
  src/radical/pilot/pilot_manager.py
  src/radical/pilot/raptor/worker_default.py
Labels: topic:documentation, topic:api, type:enhancement, priority:medium, comp:tmgr

#2932 fix a dict entry
  src/radical/pilot/raptor/master.py
Labels: type:bug, topic:data, priority:medium, comp:raptor

#2937 Fix/raptor env
  src/radical/pilot/agent/agent_0.py
Labels: type:bug, topic:resource, priority:high, comp:agent, topic:deployment

#2936 added configuration and description for Perlmutter@NERSC
  docs/source/supported/bridges2.rst
  docs/source/supported/perlmutter.rst
  docs/source/supported/polaris.rst
  docs/source/supported/rivanna.rst
  src/radical/pilot/configs/resource_nersc.json
Labels: type:feature, topic:documentation, topic:resource

#2941 Addresses ticket #1577
  docs/bin/lm_parser.py
  docs/source/internals.rst
  docs/source/supported.rst
Labels: topic:documentation

#2940 Docs/supported amarel
  docs/source/supported/amarel.rst
  docs/source/supported/bridges2.rst
  docs/source/supported/rivanna.rst
Labels: topic:documentation, topic:resource

#2944 fixed error handling in git call
  .github/workflows/ci.yml
Labels: type:bug, topic:testing

#2946 added supported platform Summit (docs)
  docs/source/supported/summit.rst
Labels: topic:documentation, topic:resource

#2934 Docs/nb section3 debug
  docs/source/tutorials/debugging.ipynb
  src/radical/pilot/agent/executing/popen.py
  src/radical/pilot/configs/resource_local.json
  src/radical/pilot/pmgr/launching/base.py
  tests/unit_tests/test_executing/test_popen.py
  tests/unit_tests/test_scheduler/test_base.py
Labels: topic:documentation, topic:api, type:enhancement, topic:deployment

#2950 added env var `SLURM_JOB_NODELIST` for Slurm RM
  src/radical/pilot/agent/resource_manager/slurm.py
  tests/unit_tests/test_rm/test_slurm.py
Labels: type:bug, topic:resource, priority:high
