Repository radical-cybertools/radical.pilot, pull requests merged in 2024-01, with the labels that each got.

#3107 fixed tasks handling in `prof_utils`
  src/radical/pilot/agent/scheduler/base.py
  src/radical/pilot/utils/prof_utils.py
Labels: type:bug, layer:analytics, priority:medium, comp:session

#3102 fix flux event management
  examples/00_getting_started.py
  examples/02_failing_tasks.py
  requirements.txt
  src/radical/pilot/agent/executing/flux.py
  src/radical/pilot/agent/launch_method/flux.py
  src/radical/pilot/agent/scheduler/flux.py
  src/radical/pilot/configs/resource_debug.json
  src/radical/pilot/utils/component.py
Labels: type:bug, topic:execution, priority:high, comp:agent:executor, comp:agent:scheduler

#3118 fixed type for `LFS_SIZE_PER_NODE`
  src/radical/pilot/resource_config.py
Labels: type:bug, priority:high, comp:agent
