Repository radical-cybertools/radical.pilot, pull requests merged in 2024-10, with the labels that each got.

#3234 apply cb lock
  src/radical/pilot/pilot.py
Labels: type:bug, topic:api, priority:critical, comp:pmgr, external

#3235 remove docker folder and link the tutorial repo in the README
  README.md
  docker/README.md
  docker/compose.yml
  docker/radicalpilot.dockerfile
  docker/rp-complete.dockerfile
Labels: topic:documentation, type:enhancement, layer:rp, priority:medium, internal

#3215 initial implementation of task priorities
  examples/misc/task_priorities.py
  src/radical/pilot/agent/scheduler/base.py
  src/radical/pilot/task_description.py
  tests/unit_tests/test_scheduler/test_base.py
  tests/unit_tests/test_scheduler/test_continuous.py
Labels: type:feature, topic:api, comp:agent:scheduler, external

#3222 add examples as integration tests
  .github/workflows/ci-release.yml
  .github/workflows/ci.yml
  examples/01_task_details.py
  examples/02_failing_tasks.py
  examples/03_multiple_pilots.py
  examples/04_scheduler_selection.py
  examples/05_task_input_data.py
  examples/06_task_output_data.py
  examples/07_shared_task_data.py
  examples/08_task_environment.py
  examples/09_mpi_tasks.py
  examples/10_pre_and_post_exec.py
  examples/11_task_input_data_tar.py
  examples/11_task_input_folder.py
  examples/12_task_env.py
Labels: topic:testing, type:enhancement, priority:medium, internal

#3199 Feature/numa domains
  examples/misc/pilot_resources.py
  src/radical/pilot/__init__.py
  src/radical/pilot/agent/launch_method/base.py
  src/radical/pilot/agent/resource_manager/base.py
  src/radical/pilot/configs/resource_ornl.json
  src/radical/pilot/pilot.py
  src/radical/pilot/pmgr/launching/base.py
  src/radical/pilot/resource_config.py
  tests/unit_tests/test_rm/test_base.py
Labels: topic:resource, type:enhancement, priority:medium, external

#3236 use pwatcher
  bin/radical-pilot-agent_0
  bin/radical-pilot-agent_n
  bin/radical-pilot-bridge
  bin/radical-pilot-component
  src/radical/pilot/agent/bootstrap_0.sh
  src/radical/pilot/utils/component.py
  src/radical/pilot/utils/component_manager.py
Labels: type:bug, topic:termination, priority:critical, comp:session, external

#3243 Service Startup III
  examples/misc/service_tasks.py
  src/radical/pilot/agent/agent_0.py
  src/radical/pilot/pilot.py
Labels: type:feature, topic:api, priority:high, comp:pmgr, external

#3038 Upload sessions of analytics tests
  .github/workflows/ci.yml
  .github/workflows/run-rp-notebook.yml
Labels: topic:testing, internal

#3244 Fix/server log
  src/radical/pilot/proxy.py
  src/radical/pilot/session.py
Labels: type:bug, priority:low, topic:configuration, internal

#3250 we expect task metadata to be a dict - enforce and document
  src/radical/pilot/task_description.py
  tests/integration_tests/test_lm/test_mpirun.py
Labels: type:bug, topic:documentation, topic:api, priority:low, comp:session, internal
