Repository radical-cybertools/radical.pilot, pull requests merged in 2024-07, with the labels that each got.

#3210 fixed node indexing for analytics (RA)
  src/radical/pilot/utils/prof_utils.py
Labels: type:bug, layer:analytics, internal

#3212 update Rivanna config
  src/radical/pilot/configs/resource_uva.json
Labels: topic:configuration, internal

#3217 ensure that stdout/stderr strings are utf8
  src/radical/pilot/agent/staging_output/default.py
Labels: type:bug, topic:data, topic:execution, priority:high, comp:agent:stager, external
